modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="ctp"
version="1.0.0"
displayName="Craftopia"
credits="Created By Craftopia Development Community"
displayURL="https://github.com/Sammythybunnie67/Craftopia"
authors="sammythybunnie67"
description='''
Craftopia is a mod that aims to improve minecraft in many ways
'''

[[dependencies.ctp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




